import { test } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://nextjs-app-yvfr.vercel.app/user');
  await page.getByRole('button', { name: 'ログアウト' }).click();
  await page.getByRole('button', { name: 'ログアウト' }).click();
  await page.goto('https://nextjs-app-yvfr.vercel.app/');
  await page.getByRole('link', { name: 'ログイン' }).click();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('');
  await page.getByRole('textbox', { name: 'Email' }).fill('Eisu');
  await page.getByRole('textbox', { name: 'Email' }).fill('darry6335@gmail.com');
  await page.getByRole('textbox', { name: 'Email' }).press('Tab');
  await page.getByRole('textbox', { name: 'Password' }).fill('123');
  await page.getByRole('button', { name: 'ログイン' }).click();
  await page.getByRole('link', { name: '記事を書く' }).click();
  await page.getByRole('textbox', { name: 'タイトル' }).click();
  await page.getByRole('textbox', { name: 'タイトル' }).fill('KanjiMode');
  await page.getByRole('textbox', { name: 'タイトル' }).press('Tab');
  await page.getByRole('textbox', { name: '記事本文' }).fill('テスト');
  await page.getByRole('button', { name: 'キャンセル' }).click();
  await page.getByRole('link', { name: '記事を書く' }).click();
  await page.getByRole('textbox', { name: 'タイトル' }).click();
  await page.getByRole('textbox', { name: 'タイトル' }).fill('公開');
  await page.getByRole('textbox', { name: 'タイトル' }).press('Enter');
  await page.getByRole('textbox', { name: 'タイトル' }).press('Tab');
  await page.getByRole('textbox', { name: '記事本文' }).fill('テスト');
  await page.getByRole('textbox', { name: '記事本文' }).press('Tab');
  await page.getByRole('button', { name: '下書き保存' }).press('Tab');
  await page.getByRole('button', { name: '公開する' }).click();
  await page.getByRole('button', { name: '公開する' }).click();
  await page.getByRole('link', { name: '記事を書く' }).click();
  await page.getByRole('textbox', { name: 'タイトル' }).click();
  await page.getByRole('textbox', { name: 'タイトル' }).fill('KanjiMode');
  await page.getByRole('textbox', { name: '記事本文' }).click();
  await page.getByRole('textbox', { name: '記事本文' }).fill('テスト');
  await page.getByRole('button', { name: '下書き保存' }).click();
  await page.getByRole('link', { name: '記事を編集する' }).click();
  await page.getByRole('button', { name: 'select article' }).click();
  await page.getByRole('menuitem', { name: 'test' }).click();
  await page.getByRole('textbox', { name: '本文' }).click();
  await page.getByRole('textbox', { name: '本文' }).fill('test\n');
  await page.getByRole('textbox', { name: '本文' }).fill('KanjiMode');
  await page.getByRole('textbox', { name: '本文' }).fill('test\n編集のテスト');
  await page.getByRole('textbox', { name: '本文' }).click();
  await page.getByRole('textbox', { name: '本文' }).fill('test\n編集のキャンセル');
  await page.getByRole('button', { name: 'キャンセル' }).click();
  await page.getByRole('link', { name: '記事を編集する' }).click();
  await page.getByRole('button', { name: '戻る' }).click();
  await page.getByRole('link', { name: '記事を編集する' }).click();
  await page.getByRole('button', { name: 'select article' }).click();
  await page.getByRole('menuitem', { name: 'test' }).click();
  await page.getByRole('textbox', { name: '本文' }).click();
  await page.getByRole('textbox', { name: '本文' }).fill('編集');
  await page.getByRole('button', { name: '公開' }).click();
  await page.getByRole('button', { name: '確認' }).click();
  await page.getByRole('link', { name: '記事を編集する' }).click();
  await page.getByRole('button', { name: 'select article' }).click();
  await page.getByRole('menuitem', { name: 'test' }).click();
  await page.getByRole('textbox', { name: '本文' }).click();
  await page.getByRole('textbox', { name: '本文' }).fill('編集\n\n下書き');
  await page.getByRole('button', { name: '下書き保存' }).click();
  await page.getByRole('button', { name: '確認' }).click();
  await page.getByRole('link', { name: '記事を削除する' }).click();
  await page.getByRole('button', { name: '会員専用ページに戻る' }).click();
  await page.getByRole('link', { name: '記事を削除する' }).click();
  await page.getByRole('listitem').filter({ hasText: 'KanjiMode' }).getByLabel('delete').first().click();
  await page.getByRole('button', { name: '削除' }).click();
  await page.getByRole('listitem').filter({ hasText: 'test' }).getByLabel('delete').first().click();
  await page.getByRole('button', { name: 'キャンセル' }).click();
  await page.getByRole('button', { name: '会員専用ページに戻る' }).click();
});