name: E2E Tests
on:
  schedule:
    - cron: '0 2 * * *'  # 毎日午前2時
  push:
    branches: [main]
jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run E2E Tests
        run: npm run test:e2e
